[project]
name = "aerosim-knowledge-navigator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "wgx", email = "1006059169@qq.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
aerosim-knowledge-navigator = "aerosim_knowledge_navigator:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"
